akashic-games/pdi-types

src/asset/Asset.ts, src/asset/audio/AudioAsset.ts, src/font/Glyph.ts, src/surface/Renderer.ts
掲題どおり。リポジトリ分割に前後してマージされた akashic-games/akashic-engine#235 を取り込みます。
自明につきセルフマージします。
=> add @ignore annotation (merge akashic-engine #235)

CHANGELOG.md, package-lock.json, package.json, test/pdi-build-test.ts
内部モジュールを更新します。
https://github.com/akashic-games/akashic-pdi/pull/19 と同様の修正のためセルフマージします。
=> Update internal modules

.github/workflows/test.yml, .travis.yml, CHANGELOG.md, package-lock.json, package.json, src/surface/Renderer.ts
`Renderer#_getImageData()` の戻り値の型を、仕様通りの `ImageData | null` に修正します。
=> Fix the return value type of Renderer#_getImageData()

CHANGELOG.md, package-lock.json, package.json
=> deps: use amflow@3.1.0

CHANGELOG.md, package-lock.json, package.json
@akashic/trigger の patch 更新に伴うバージョンアップ
セルフマージとします。
=> Bump version to 1.3.1

.github/workflows/release.yml, .github/workflows/test.yml
CI の Node のバージョンを 14, 16 に更新します。他リポジトリでの同様の修正はレビュー済みのためセルフマージします。
=> chore: use Node 14, 16

renovate.json
* renovate.json を共通設定に変更
すでに同様の修正はレビュー済みのためセルフマージします。
=> chore: use shareable presets

.editorconfig, .eslintrc.json, .github/workflows/release.yml, CHANGELOG.md, README.md, package-lock.json, package.json, src/platform/ResourceFactory.ts, test/.eslintrc.json, test/pdi-build-test.ts
`ResourceFactory#createVectorImageAssetFromString()` を追加します。
=> feat: add `createVectorImageAssetFromString()`

.editorconfig, .eslintrc.json, .github/workflows/release.yml, CHANGELOG.md, README.md, package-lock.json, package.json, src/platform/ResourceFactory.ts, test/.eslintrc.json, test/pdi-build-test.ts
=> Release 1.4.0

CHANGELOG.md, test/pdi-build-test.ts
CHANGELOG.md を修正します。自明な変更のためセルフマージします。
=> chore: fix CHANGELOG.md

src/asset/audio/AudioAsset.ts
オーディオアセットのプロパティを変更してはならない旨をコメントに追加します。
- なし
=> add readonly comment

CHANGELOG.md, package-lock.json, package.json, src/asset/audio/AudioAssetHint.ts
* AudioAssetで利用する拡張子を指定できるようにするために、`AudioAssetHint#extensions` を追加
=> add AudioAssetHint#extensions

.github/workflows/release.yml, .github/workflows/test.yml
=> Mod CI node version to v18

CHANGELOG.md, package-lock.json, package.json
`@akashic/trigger` を 2.0.0 に更新します。
=> chore(deps): update trigger@2.0.0

CHANGELOG.md, package-lock.json, package.json, src/platform/PlatformPointEvent.ts
* Akashic Engineでマウスクリックの際にどのボタンが押されたか認識できるようにするためにボタンの種類に関する型と`PlatformPointEvent#button`というプロパティを追加しました。
=> add PlatformPointEvent#button

CHANGELOG.md, package-lock.json, package.json, src/asset/binary/BinaryAsset.ts, src/asset/script/ScriptAsset.ts, src/index.ts, src/platform/ResourceFactory.ts, test/pdi-build-test.ts
akashic-games/game-configuration/pull/40 および akashic-games/game-configuration/pull/41 の pdi-types 側の対応です。
=> feat: BinaryAsset の追加および ScriptAsset#exports の追加

CHANGELOG.md, package-lock.json, package.json
* `@akashic/amflow`と`@akashic/playlog`を最新バージョンに更新
=> update akashic modules

.github/workflows/test.yml, CHANGELOG.md, package-lock.json, package.json, src/platform/PlatformPointEvent.ts
`PlatformButtonType` に直前から変化がない場合の値 `-1` を追加します。
ref. https://w3c.github.io/pointerevents/#the-button-property
=> feat: add unchanged flag to PlatformButtonType

.github/workflows/release.yml, .github/workflows/test.yml, package-lock.json, package.json
依存モジュールを更新します。
自明な修正のためセルフマージします。
=> chore(deps): update internal modules

CHANGELOG.md, package-lock.json, package.json, src/index.ts, src/platform/RendererCandidate.ts, src/platform/RendererRequirement.ts
* `RendererCandidate` を追加します
* `RendererRequirement#rendererCandidates` の型を `(string | RendererCandidate)[]` に変更します
=> feat: add RendererCandidate
